---

- hosts: all
  become: true
  tasks:


  - name: install apache and php package for Ubuntu servers
    apt:
      name: apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and ph for Rocky servers
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"
